# Site settings
title: I'm Matt Miller.
email: matthew.josiah.miller@gmail.com
description: > Researcher, writer, and Midwesterner, I work in marketing by day and do scholarship at teaching otherwise.
  My site for demonstrating how to build a Jekyll website hosted on GitHub Pages, built for a Programming Historian lesson.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  matthewjmiller

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
